apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  createNamespace: true
  repo: https://charts.jetstack.io
  set:
    installCRDs: 'true'
  targetNamespace: cert-manager
  version: 1.12.4
