apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ngrok-ingress-controller
  namespace: kube-system
spec:
  chart: kubernetes-ingress-controller
  createNamespace: true
  repo: https://ngrok.github.io/kubernetes-ingress-controller
  set:
    credentials.apiKey: REDACTED
    credentials.authtoken: REDACTED
  targetNamespace: ngrok
  version: 0.12.1
