apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: rancher
  createNamespace: true
  repo: https://releases.rancher.com/server-charts/stable
  targetNamespace: cattle-system
  valuesContent: |-
    bootstrapPassword: password
    certmanager.version: 1.12.4
    hostname: domain.org
    ingress:
      tls:
        source: letsEncrypt
        secretName: rancher-tls
      ingressClassName: nginx
    letsEncrypt:
      email: "youremail@domain.org"
      ingress:
        class: nginx
  version: 2.7.6
